// Generated by tests/generate_torch_transformer_fixtures.sh
// Source: tests/torch_transformer.py --mode mlir --encoder-layers 1 --decoder-layers 1
// Pipeline: torch-mlir-opt --torch-backend-to-linalg-on-tensors-backend-pipeline
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
#map2 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map3 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>
#map4 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, 0)>
#map5 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>
#map6 = affine_map<(d0, d1, d2) -> (d0, d1, 0)>
#map7 = affine_map<(d0, d1, d2) -> (d2)>
#map8 = affine_map<(d0) -> (d0)>
#map9 = affine_map<(d0, d1) -> (d0, 0)>
#map10 = affine_map<(d0, d1) -> (0, d1)>
module {
  func.func @forward(%arg0: tensor<1x3x4xf32>, %arg1: tensor<1x3x4xf32>) -> tensor<1x3x4xf32> {
    %cst = arith.constant dense_resource<torch_tensor_12_4_torch.float32> : tensor<12x4xf32>
    %c4_i64 = arith.constant 4 : i64
    %c0_i64 = arith.constant 0 : i64
    %cst_0 = arith.constant 0.000000e+00 : f32
    %c12_i64 = arith.constant 12 : i64
    %cst_1 = arith.constant 0xFF800000 : f32
    %cst_2 = arith.constant 0.000000e+00 : f64
    %false = arith.constant false
    %cst_3 = arith.constant 1.000000e+00 : f32
    %cst_4 = arith.constant 5.000000e-01 : f32
    %c48_i64 = arith.constant 48 : i64
    %cst_5 = arith.constant 1.000000e-05 : f64
    %cst_6 = arith.constant 0xFFF0000000000000 : f64
    %cst_7 = arith.constant 0.8408964152537145 : f64
    %cst_8 = arith.constant 4.000000e+00 : f64
    %cst_9 = arith.constant 4.000000e+00 : f32
    %cst_10 = arith.constant 1.41421354 : f32
    %cst_11 = arith.constant dense_resource<torch_tensor_12_torch.float32> : tensor<12xf32>
    %cst_12 = arith.constant dense_resource<torch_tensor_4_4_torch.float32> : tensor<4x4xf32>
    %cst_13 = arith.constant dense_resource<torch_tensor_4_torch.float32> : tensor<4xf32>
    %cst_14 = arith.constant dense_resource<torch_tensor_4_torch.float32_1> : tensor<4xf32>
    %cst_15 = arith.constant dense_resource<torch_tensor_4_torch.float32_2> : tensor<4xf32>
    %cst_16 = arith.constant dense_resource<torch_tensor_8_4_torch.float32> : tensor<8x4xf32>
    %cst_17 = arith.constant dense_resource<torch_tensor_8_torch.float32> : tensor<8xf32>
    %cst_18 = arith.constant dense_resource<torch_tensor_4_8_torch.float32> : tensor<4x8xf32>
    %cst_19 = arith.constant dense_resource<torch_tensor_4_torch.float32_3> : tensor<4xf32>
    %cst_20 = arith.constant dense_resource<torch_tensor_4_torch.float32_4> : tensor<4xf32>
    %cst_21 = arith.constant dense_resource<torch_tensor_4_torch.float32_5> : tensor<4xf32>
    %cst_22 = arith.constant dense_resource<torch_tensor_4_torch.float32_6> : tensor<4xf32>
    %cst_23 = arith.constant dense_resource<torch_tensor_4_torch.float32_7> : tensor<4xf32>
    %cst_24 = arith.constant dense_resource<torch_tensor_12_4_torch.float32_1> : tensor<12x4xf32>
    %cst_25 = arith.constant dense_resource<torch_tensor_12_torch.float32_1> : tensor<12xf32>
    %cst_26 = arith.constant dense_resource<torch_tensor_4_4_torch.float32_1> : tensor<4x4xf32>
    %cst_27 = arith.constant dense_resource<torch_tensor_4_torch.float32_8> : tensor<4xf32>
    %cst_28 = arith.constant dense_resource<torch_tensor_4_torch.float32_9> : tensor<4xf32>
    %cst_29 = arith.constant dense_resource<torch_tensor_4_torch.float32_10> : tensor<4xf32>
    %cst_30 = arith.constant dense_resource<torch_tensor_12_4_torch.float32_2> : tensor<12x4xf32>
    %cst_31 = arith.constant dense_resource<torch_tensor_12_torch.float32_2> : tensor<12xf32>
    %cst_32 = arith.constant dense_resource<torch_tensor_4_4_torch.float32_2> : tensor<4x4xf32>
    %cst_33 = arith.constant dense_resource<torch_tensor_4_torch.float32_11> : tensor<4xf32>
    %cst_34 = arith.constant dense_resource<torch_tensor_4_torch.float32_12> : tensor<4xf32>
    %cst_35 = arith.constant dense_resource<torch_tensor_4_torch.float32_13> : tensor<4xf32>
    %cst_36 = arith.constant dense_resource<torch_tensor_8_4_torch.float32_1> : tensor<8x4xf32>
    %cst_37 = arith.constant dense_resource<torch_tensor_8_torch.float32_1> : tensor<8xf32>
    %cst_38 = arith.constant dense_resource<torch_tensor_4_8_torch.float32_1> : tensor<4x8xf32>
    %cst_39 = arith.constant dense_resource<torch_tensor_4_torch.float32_14> : tensor<4xf32>
    %cst_40 = arith.constant dense_resource<torch_tensor_4_torch.float32_15> : tensor<4xf32>
    %cst_41 = arith.constant dense_resource<torch_tensor_4_torch.float32_16> : tensor<4xf32>
    %cst_42 = arith.constant dense_resource<torch_tensor_4_torch.float32_17> : tensor<4xf32>
    %cst_43 = arith.constant dense_resource<torch_tensor_4_torch.float32_18> : tensor<4xf32>
    %cst_44 = arith.constant dense<0.000000e+00> : tensor<1x2x3x3xf32>
    %c16_i64 = arith.constant 16 : i64
    %0 = tensor.empty() : tensor<3x1x4xf32>
    %transposed = linalg.transpose ins(%arg0 : tensor<1x3x4xf32>) outs(%0 : tensor<3x1x4xf32>) permutation = [1, 0, 2] 
    %collapsed = tensor.collapse_shape %transposed [[0], [1, 2]] : tensor<3x1x4xf32> into tensor<3x4xf32>
    %1 = tensor.empty() : tensor<4x12xf32>
    %transposed_45 = linalg.transpose ins(%cst : tensor<12x4xf32>) outs(%1 : tensor<4x12xf32>) permutation = [1, 0] 
    %2 = tensor.empty() : tensor<3x12xf32>
    %3 = linalg.fill ins(%cst_0 : f32) outs(%2 : tensor<3x12xf32>) -> tensor<3x12xf32>
    %4 = linalg.matmul ins(%collapsed, %transposed_45 : tensor<3x4xf32>, tensor<4x12xf32>) outs(%3 : tensor<3x12xf32>) -> tensor<3x12xf32>
    %5 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%4, %cst_11 : tensor<3x12xf32>, tensor<12xf32>) outs(%2 : tensor<3x12xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x12xf32>
    %expanded = tensor.expand_shape %5 [[0, 1], [2, 3, 4]] output_shape [1, 3, 1, 3, 4] : tensor<3x12xf32> into tensor<1x3x1x3x4xf32>
    %6 = tensor.empty() : tensor<3x3x1x1x4xf32>
    %transposed_46 = linalg.transpose ins(%expanded : tensor<1x3x1x3x4xf32>) outs(%6 : tensor<3x3x1x1x4xf32>) permutation = [3, 1, 2, 0, 4] 
    %collapsed_47 = tensor.collapse_shape %transposed_46 [[0], [1], [2, 3], [4]] : tensor<3x3x1x1x4xf32> into tensor<3x3x1x4xf32>
    %extracted_slice = tensor.extract_slice %collapsed_47[0, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %extracted_slice_48 = tensor.extract_slice %collapsed_47[1, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %extracted_slice_49 = tensor.extract_slice %collapsed_47[2, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %collapsed_50 = tensor.collapse_shape %extracted_slice [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_51 = tensor.expand_shape %collapsed_50 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %7 = tensor.empty() : tensor<2x3x2xf32>
    %transposed_52 = linalg.transpose ins(%expanded_51 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_53 = tensor.collapse_shape %extracted_slice_48 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_54 = tensor.expand_shape %collapsed_53 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_55 = linalg.transpose ins(%expanded_54 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_56 = tensor.collapse_shape %extracted_slice_49 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_57 = tensor.expand_shape %collapsed_56 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_58 = linalg.transpose ins(%expanded_57 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %expanded_59 = tensor.expand_shape %transposed_52 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %expanded_60 = tensor.expand_shape %transposed_55 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %8 = tensor.empty() : tensor<1x2x3x2xf32>
    %9 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_59 : tensor<1x2x3x2xf32>) outs(%8 : tensor<1x2x3x2xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x3x2xf32>
    %10 = tensor.empty() : tensor<1x2x2x3xf32>
    %transposed_61 = linalg.transpose ins(%expanded_60 : tensor<1x2x3x2xf32>) outs(%10 : tensor<1x2x2x3xf32>) permutation = [0, 1, 3, 2] 
    %11 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%transposed_61 : tensor<1x2x2x3xf32>) outs(%10 : tensor<1x2x2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x2x3xf32>
    %collapsed_62 = tensor.collapse_shape %9 [[0, 1], [2], [3]] : tensor<1x2x3x2xf32> into tensor<2x3x2xf32>
    %collapsed_63 = tensor.collapse_shape %11 [[0, 1], [2], [3]] : tensor<1x2x2x3xf32> into tensor<2x2x3xf32>
    %12 = tensor.empty() : tensor<2x3x3xf32>
    %13 = linalg.fill ins(%cst_0 : f32) outs(%12 : tensor<2x3x3xf32>) -> tensor<2x3x3xf32>
    %14 = linalg.batch_matmul ins(%collapsed_62, %collapsed_63 : tensor<2x3x2xf32>, tensor<2x2x3xf32>) outs(%13 : tensor<2x3x3xf32>) -> tensor<2x3x3xf32>
    %expanded_64 = tensor.expand_shape %14 [[0, 1], [2], [3]] output_shape [1, 2, 3, 3] : tensor<2x3x3xf32> into tensor<1x2x3x3xf32>
    %15 = tensor.empty() : tensor<1x2x3xi64>
    %16 = linalg.fill ins(%c0_i64 : i64) outs(%15 : tensor<1x2x3xi64>) -> tensor<1x2x3xi64>
    %17 = tensor.empty() : tensor<1x2x3xf32>
    %18 = linalg.fill ins(%cst_1 : f32) outs(%17 : tensor<1x2x3xf32>) -> tensor<1x2x3xf32>
    %19:2 = linalg.generic {indexing_maps = [#map2, #map3, #map3], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%expanded_64 : tensor<1x2x3x3xf32>) outs(%18, %16 : tensor<1x2x3xf32>, tensor<1x2x3xi64>) {
    ^bb0(%in: f32, %out: f32, %out_158: i64):
      %243 = linalg.index 3 : index
      %244 = arith.index_cast %243 : index to i64
      %245 = arith.maximumf %in, %out : f32
      %246 = arith.cmpf ogt, %in, %out : f32
      %247 = arith.select %246, %244, %out_158 : i64
      linalg.yield %245, %247 : f32, i64
    } -> (tensor<1x2x3xf32>, tensor<1x2x3xi64>)
    %expanded_65 = tensor.expand_shape %19#0 [[0], [1], [2, 3]] output_shape [1, 2, 3, 1] : tensor<1x2x3xf32> into tensor<1x2x3x1xf32>
    %20 = tensor.empty() : tensor<1x2x3x3xf32>
    %21 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_64, %expanded_65 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %22 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%21 : tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.exp %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %23 = tensor.empty() : tensor<1x2x3x1xf32>
    %24 = linalg.fill ins(%cst_0 : f32) outs(%23 : tensor<1x2x3x1xf32>) -> tensor<1x2x3x1xf32>
    %25 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%22 : tensor<1x2x3x3xf32>) outs(%24 : tensor<1x2x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x1xf32>
    %26 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%22, %25 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.divf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %27 = tensor.empty() : tensor<1x2x3x3xi1>
    %28 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_64 : tensor<1x2x3x3xf32>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: f32, %out: i1):
      %243 = arith.extf %in : f32 to f64
      %244 = arith.cmpf oeq, %243, %cst_6 : f64
      linalg.yield %244 : i1
    } -> tensor<1x2x3x3xi1>
    %29 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%28 : tensor<1x2x3x3xi1>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x3xi1>
    %30 = tensor.empty() : tensor<1x2x3x1xi1>
    %31 = linalg.fill ins(%false : i1) outs(%30 : tensor<1x2x3x1xi1>) -> tensor<1x2x3x1xi1>
    %32 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%29 : tensor<1x2x3x3xi1>) outs(%31 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.ori %in, %out : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %33 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%32 : tensor<1x2x3x1xi1>) outs(%30 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %34 = linalg.generic {indexing_maps = [#map4, #map2, #map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%33, %cst_44, %26 : tensor<1x2x3x1xi1>, tensor<1x2x3x3xf32>, tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: i1, %in_158: f32, %in_159: f32, %out: f32):
      %243 = arith.select %in, %in_158, %in_159 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %collapsed_66 = tensor.collapse_shape %34 [[0, 1], [2], [3]] : tensor<1x2x3x3xf32> into tensor<2x3x3xf32>
    %35 = linalg.fill ins(%cst_0 : f32) outs(%7 : tensor<2x3x2xf32>) -> tensor<2x3x2xf32>
    %36 = linalg.batch_matmul ins(%collapsed_66, %transposed_58 : tensor<2x3x3xf32>, tensor<2x3x2xf32>) outs(%35 : tensor<2x3x2xf32>) -> tensor<2x3x2xf32>
    %expanded_67 = tensor.expand_shape %36 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %37 = tensor.empty() : tensor<3x1x2x2xf32>
    %transposed_68 = linalg.transpose ins(%expanded_67 : tensor<1x2x3x2xf32>) outs(%37 : tensor<3x1x2x2xf32>) permutation = [2, 0, 1, 3] 
    %collapsed_69 = tensor.collapse_shape %transposed_68 [[0], [1, 2, 3]] : tensor<3x1x2x2xf32> into tensor<3x4xf32>
    %38 = tensor.empty() : tensor<4x4xf32>
    %transposed_70 = linalg.transpose ins(%cst_12 : tensor<4x4xf32>) outs(%38 : tensor<4x4xf32>) permutation = [1, 0] 
    %39 = tensor.empty() : tensor<3x4xf32>
    %40 = linalg.fill ins(%cst_0 : f32) outs(%39 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %41 = linalg.matmul ins(%collapsed_69, %transposed_70 : tensor<3x4xf32>, tensor<4x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %42 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%41, %cst_13 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %expanded_71 = tensor.expand_shape %42 [[0], [1, 2]] output_shape [3, 1, 4] : tensor<3x4xf32> into tensor<3x1x4xf32>
    %43 = tensor.empty() : tensor<1x3x4xf32>
    %transposed_72 = linalg.transpose ins(%expanded_71 : tensor<3x1x4xf32>) outs(%43 : tensor<1x3x4xf32>) permutation = [1, 0, 2] 
    %44 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg0, %transposed_72 : tensor<1x3x4xf32>, tensor<1x3x4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %45 = tensor.empty() : tensor<1x3x4xf64>
    %46 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%44 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %47 = tensor.empty() : tensor<1x3x1xf64>
    %48 = linalg.fill ins(%cst_2 : f64) outs(%47 : tensor<1x3x1xf64>) -> tensor<1x3x1xf64>
    %49 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%46 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %50 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%49 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %51 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%46, %50 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %52 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%51, %51 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %53 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%52 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %54 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%53 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %55 = tensor.empty() : tensor<1x3x1xf32>
    %56 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%54 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %57 = linalg.fill ins(%cst_0 : f32) outs(%55 : tensor<1x3x1xf32>) -> tensor<1x3x1xf32>
    %58 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%44 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %59 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%58 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %60 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%56 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %61 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%60 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %62 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%44, %59 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %63 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%62, %61 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %64 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%63, %cst_14 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %65 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%64, %cst_15 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %collapsed_73 = tensor.collapse_shape %65 [[0, 1], [2]] : tensor<1x3x4xf32> into tensor<3x4xf32>
    %66 = tensor.empty() : tensor<4x8xf32>
    %transposed_74 = linalg.transpose ins(%cst_16 : tensor<8x4xf32>) outs(%66 : tensor<4x8xf32>) permutation = [1, 0] 
    %67 = tensor.empty() : tensor<3x8xf32>
    %68 = linalg.fill ins(%cst_0 : f32) outs(%67 : tensor<3x8xf32>) -> tensor<3x8xf32>
    %69 = linalg.matmul ins(%collapsed_73, %transposed_74 : tensor<3x4xf32>, tensor<4x8xf32>) outs(%68 : tensor<3x8xf32>) -> tensor<3x8xf32>
    %70 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%69, %cst_17 : tensor<3x8xf32>, tensor<8xf32>) outs(%67 : tensor<3x8xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x8xf32>
    %expanded_75 = tensor.expand_shape %70 [[0, 1], [2]] output_shape [1, 3, 8] : tensor<3x8xf32> into tensor<1x3x8xf32>
    %71 = tensor.empty() : tensor<1x3x8xf32>
    %72 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_75 : tensor<1x3x8xf32>) outs(%71 : tensor<1x3x8xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_10 : f32
      %244 = math.erf %243 : f32
      %245 = arith.addf %244, %cst_3 : f32
      %246 = arith.mulf %245, %cst_4 : f32
      %247 = arith.mulf %in, %246 : f32
      linalg.yield %247 : f32
    } -> tensor<1x3x8xf32>
    %collapsed_76 = tensor.collapse_shape %72 [[0, 1], [2]] : tensor<1x3x8xf32> into tensor<3x8xf32>
    %73 = tensor.empty() : tensor<8x4xf32>
    %transposed_77 = linalg.transpose ins(%cst_18 : tensor<4x8xf32>) outs(%73 : tensor<8x4xf32>) permutation = [1, 0] 
    %74 = linalg.matmul ins(%collapsed_76, %transposed_77 : tensor<3x8xf32>, tensor<8x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %75 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%74, %cst_19 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %expanded_78 = tensor.expand_shape %75 [[0, 1], [2]] output_shape [1, 3, 4] : tensor<3x4xf32> into tensor<1x3x4xf32>
    %76 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%65, %expanded_78 : tensor<1x3x4xf32>, tensor<1x3x4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %77 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%76 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %78 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%77 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %79 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%78 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %80 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%77, %79 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %81 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%80, %80 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %82 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%81 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %83 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%82 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %84 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%83 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %85 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%76 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %86 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%85 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %87 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%84 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %88 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%87 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %89 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%76, %86 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %90 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%89, %88 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %91 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%90, %cst_20 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %92 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%91, %cst_21 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %93 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%92 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %94 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%93 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %95 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%94 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %96 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%93, %95 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %97 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%96, %96 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %98 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%97 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %99 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%98 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %100 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%99 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %101 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%92 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %102 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%101 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %103 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%100 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %104 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%103 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %105 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%92, %102 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %106 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%105, %104 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %107 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%106, %cst_22 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %108 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%107, %cst_23 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %transposed_79 = linalg.transpose ins(%arg1 : tensor<1x3x4xf32>) outs(%0 : tensor<3x1x4xf32>) permutation = [1, 0, 2] 
    %collapsed_80 = tensor.collapse_shape %transposed_79 [[0], [1, 2]] : tensor<3x1x4xf32> into tensor<3x4xf32>
    %transposed_81 = linalg.transpose ins(%cst_24 : tensor<12x4xf32>) outs(%1 : tensor<4x12xf32>) permutation = [1, 0] 
    %109 = linalg.matmul ins(%collapsed_80, %transposed_81 : tensor<3x4xf32>, tensor<4x12xf32>) outs(%3 : tensor<3x12xf32>) -> tensor<3x12xf32>
    %110 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%109, %cst_25 : tensor<3x12xf32>, tensor<12xf32>) outs(%2 : tensor<3x12xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x12xf32>
    %expanded_82 = tensor.expand_shape %110 [[0, 1], [2, 3, 4]] output_shape [1, 3, 1, 3, 4] : tensor<3x12xf32> into tensor<1x3x1x3x4xf32>
    %transposed_83 = linalg.transpose ins(%expanded_82 : tensor<1x3x1x3x4xf32>) outs(%6 : tensor<3x3x1x1x4xf32>) permutation = [3, 1, 2, 0, 4] 
    %collapsed_84 = tensor.collapse_shape %transposed_83 [[0], [1], [2, 3], [4]] : tensor<3x3x1x1x4xf32> into tensor<3x3x1x4xf32>
    %extracted_slice_85 = tensor.extract_slice %collapsed_84[0, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %extracted_slice_86 = tensor.extract_slice %collapsed_84[1, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %extracted_slice_87 = tensor.extract_slice %collapsed_84[2, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<3x3x1x4xf32> to tensor<1x3x1x4xf32>
    %collapsed_88 = tensor.collapse_shape %extracted_slice_85 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_89 = tensor.expand_shape %collapsed_88 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_90 = linalg.transpose ins(%expanded_89 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_91 = tensor.collapse_shape %extracted_slice_86 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_92 = tensor.expand_shape %collapsed_91 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_93 = linalg.transpose ins(%expanded_92 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_94 = tensor.collapse_shape %extracted_slice_87 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_95 = tensor.expand_shape %collapsed_94 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_96 = linalg.transpose ins(%expanded_95 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %expanded_97 = tensor.expand_shape %transposed_90 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %expanded_98 = tensor.expand_shape %transposed_93 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %111 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_97 : tensor<1x2x3x2xf32>) outs(%8 : tensor<1x2x3x2xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x3x2xf32>
    %transposed_99 = linalg.transpose ins(%expanded_98 : tensor<1x2x3x2xf32>) outs(%10 : tensor<1x2x2x3xf32>) permutation = [0, 1, 3, 2] 
    %112 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%transposed_99 : tensor<1x2x2x3xf32>) outs(%10 : tensor<1x2x2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x2x3xf32>
    %collapsed_100 = tensor.collapse_shape %111 [[0, 1], [2], [3]] : tensor<1x2x3x2xf32> into tensor<2x3x2xf32>
    %collapsed_101 = tensor.collapse_shape %112 [[0, 1], [2], [3]] : tensor<1x2x2x3xf32> into tensor<2x2x3xf32>
    %113 = linalg.batch_matmul ins(%collapsed_100, %collapsed_101 : tensor<2x3x2xf32>, tensor<2x2x3xf32>) outs(%13 : tensor<2x3x3xf32>) -> tensor<2x3x3xf32>
    %expanded_102 = tensor.expand_shape %113 [[0, 1], [2], [3]] output_shape [1, 2, 3, 3] : tensor<2x3x3xf32> into tensor<1x2x3x3xf32>
    %114:2 = linalg.generic {indexing_maps = [#map2, #map3, #map3], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%expanded_102 : tensor<1x2x3x3xf32>) outs(%18, %16 : tensor<1x2x3xf32>, tensor<1x2x3xi64>) {
    ^bb0(%in: f32, %out: f32, %out_158: i64):
      %243 = linalg.index 3 : index
      %244 = arith.index_cast %243 : index to i64
      %245 = arith.maximumf %in, %out : f32
      %246 = arith.cmpf ogt, %in, %out : f32
      %247 = arith.select %246, %244, %out_158 : i64
      linalg.yield %245, %247 : f32, i64
    } -> (tensor<1x2x3xf32>, tensor<1x2x3xi64>)
    %expanded_103 = tensor.expand_shape %114#0 [[0], [1], [2, 3]] output_shape [1, 2, 3, 1] : tensor<1x2x3xf32> into tensor<1x2x3x1xf32>
    %115 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_102, %expanded_103 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %116 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%115 : tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.exp %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %117 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%116 : tensor<1x2x3x3xf32>) outs(%24 : tensor<1x2x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x1xf32>
    %118 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%116, %117 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.divf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %119 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_102 : tensor<1x2x3x3xf32>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: f32, %out: i1):
      %243 = arith.extf %in : f32 to f64
      %244 = arith.cmpf oeq, %243, %cst_6 : f64
      linalg.yield %244 : i1
    } -> tensor<1x2x3x3xi1>
    %120 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%119 : tensor<1x2x3x3xi1>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x3xi1>
    %121 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%120 : tensor<1x2x3x3xi1>) outs(%31 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.ori %in, %out : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %122 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%121 : tensor<1x2x3x1xi1>) outs(%30 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %123 = linalg.generic {indexing_maps = [#map4, #map2, #map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%122, %cst_44, %118 : tensor<1x2x3x1xi1>, tensor<1x2x3x3xf32>, tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: i1, %in_158: f32, %in_159: f32, %out: f32):
      %243 = arith.select %in, %in_158, %in_159 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %collapsed_104 = tensor.collapse_shape %123 [[0, 1], [2], [3]] : tensor<1x2x3x3xf32> into tensor<2x3x3xf32>
    %124 = linalg.batch_matmul ins(%collapsed_104, %transposed_96 : tensor<2x3x3xf32>, tensor<2x3x2xf32>) outs(%35 : tensor<2x3x2xf32>) -> tensor<2x3x2xf32>
    %expanded_105 = tensor.expand_shape %124 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %transposed_106 = linalg.transpose ins(%expanded_105 : tensor<1x2x3x2xf32>) outs(%37 : tensor<3x1x2x2xf32>) permutation = [2, 0, 1, 3] 
    %collapsed_107 = tensor.collapse_shape %transposed_106 [[0], [1, 2, 3]] : tensor<3x1x2x2xf32> into tensor<3x4xf32>
    %transposed_108 = linalg.transpose ins(%cst_26 : tensor<4x4xf32>) outs(%38 : tensor<4x4xf32>) permutation = [1, 0] 
    %125 = linalg.matmul ins(%collapsed_107, %transposed_108 : tensor<3x4xf32>, tensor<4x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %126 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%125, %cst_27 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %expanded_109 = tensor.expand_shape %126 [[0], [1, 2]] output_shape [3, 1, 4] : tensor<3x4xf32> into tensor<3x1x4xf32>
    %transposed_110 = linalg.transpose ins(%expanded_109 : tensor<3x1x4xf32>) outs(%43 : tensor<1x3x4xf32>) permutation = [1, 0, 2] 
    %127 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%arg1, %transposed_110 : tensor<1x3x4xf32>, tensor<1x3x4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %128 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%127 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %129 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%128 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %130 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%129 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %131 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%128, %130 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %132 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%131, %131 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %133 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%132 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %134 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%133 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %135 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%134 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %136 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%127 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %137 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%136 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %138 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%135 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %139 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%138 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %140 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%127, %137 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %141 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%140, %139 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %142 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%141, %cst_28 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %143 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%142, %cst_29 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %transposed_111 = linalg.transpose ins(%143 : tensor<1x3x4xf32>) outs(%0 : tensor<3x1x4xf32>) permutation = [1, 0, 2] 
    %transposed_112 = linalg.transpose ins(%108 : tensor<1x3x4xf32>) outs(%0 : tensor<3x1x4xf32>) permutation = [1, 0, 2] 
    %collapsed_113 = tensor.collapse_shape %cst_30 [[0, 1]] : tensor<12x4xf32> into tensor<48xf32>
    %144 = tensor.empty() : tensor<4xi64>
    %145 = linalg.generic {indexing_maps = [#map8], iterator_types = ["parallel"]} outs(%144 : tensor<4xi64>) {
    ^bb0(%out: i64):
      %243 = linalg.index 0 : index
      %244 = arith.index_cast %243 : index to i64
      linalg.yield %244 : i64
    } -> tensor<4xi64>
    %expanded_114 = tensor.expand_shape %145 [[0, 1]] output_shape [4, 1] : tensor<4xi64> into tensor<4x1xi64>
    %146 = tensor.empty() : tensor<4x1xi64>
    %147 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%expanded_114 : tensor<4x1xi64>) outs(%146 : tensor<4x1xi64>) {
    ^bb0(%in: i64, %out: i64):
      %243 = arith.muli %in, %c4_i64 : i64
      linalg.yield %243 : i64
    } -> tensor<4x1xi64>
    %expanded_115 = tensor.expand_shape %145 [[0, 1]] output_shape [1, 4] : tensor<4xi64> into tensor<1x4xi64>
    %148 = tensor.empty() : tensor<4x4xi64>
    %149 = linalg.generic {indexing_maps = [#map9, #map10, #map], iterator_types = ["parallel", "parallel"]} ins(%147, %expanded_115 : tensor<4x1xi64>, tensor<1x4xi64>) outs(%148 : tensor<4x4xi64>) {
    ^bb0(%in: i64, %in_158: i64, %out: i64):
      %243 = arith.addi %in, %in_158 : i64
      linalg.yield %243 : i64
    } -> tensor<4x4xi64>
    %collapsed_116 = tensor.collapse_shape %149 [[0, 1]] : tensor<4x4xi64> into tensor<16xi64>
    %150 = tensor.empty() : tensor<16xf32>
    %151 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%collapsed_116 : tensor<16xi64>) outs(%150 : tensor<16xf32>) {
    ^bb0(%in: i64, %out: f32):
      %243 = arith.cmpi slt, %in, %c0_i64 : i64
      %244 = arith.addi %in, %c48_i64 : i64
      %245 = arith.select %243, %244, %in : i64
      %246 = arith.index_cast %245 : i64 to index
      %extracted = tensor.extract %collapsed_113[%246] : tensor<48xf32>
      linalg.yield %extracted : f32
    } -> tensor<16xf32>
    %expanded_117 = tensor.expand_shape %151 [[0, 1]] output_shape [4, 4] : tensor<16xf32> into tensor<4x4xf32>
    %152 = tensor.empty() : tensor<8xi64>
    %153 = linalg.generic {indexing_maps = [#map8], iterator_types = ["parallel"]} outs(%152 : tensor<8xi64>) {
    ^bb0(%out: i64):
      %243 = linalg.index 0 : index
      %244 = arith.index_cast %243 : index to i64
      linalg.yield %244 : i64
    } -> tensor<8xi64>
    %expanded_118 = tensor.expand_shape %153 [[0, 1]] output_shape [8, 1] : tensor<8xi64> into tensor<8x1xi64>
    %154 = tensor.empty() : tensor<8x1xi64>
    %155 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%expanded_118 : tensor<8x1xi64>) outs(%154 : tensor<8x1xi64>) {
    ^bb0(%in: i64, %out: i64):
      %243 = arith.muli %in, %c4_i64 : i64
      linalg.yield %243 : i64
    } -> tensor<8x1xi64>
    %156 = tensor.empty() : tensor<8x4xi64>
    %157 = linalg.generic {indexing_maps = [#map9, #map10, #map], iterator_types = ["parallel", "parallel"]} ins(%155, %expanded_115 : tensor<8x1xi64>, tensor<1x4xi64>) outs(%156 : tensor<8x4xi64>) {
    ^bb0(%in: i64, %in_158: i64, %out: i64):
      %243 = arith.addi %in, %in_158 : i64
      linalg.yield %243 : i64
    } -> tensor<8x4xi64>
    %collapsed_119 = tensor.collapse_shape %157 [[0, 1]] : tensor<8x4xi64> into tensor<32xi64>
    %158 = tensor.empty() : tensor<32xi64>
    %159 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%collapsed_119 : tensor<32xi64>) outs(%158 : tensor<32xi64>) {
    ^bb0(%in: i64, %out: i64):
      %243 = arith.addi %in, %c16_i64 : i64
      linalg.yield %243 : i64
    } -> tensor<32xi64>
    %160 = tensor.empty() : tensor<32xf32>
    %161 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%159 : tensor<32xi64>) outs(%160 : tensor<32xf32>) {
    ^bb0(%in: i64, %out: f32):
      %243 = arith.cmpi slt, %in, %c0_i64 : i64
      %244 = arith.addi %in, %c48_i64 : i64
      %245 = arith.select %243, %244, %in : i64
      %246 = arith.index_cast %245 : i64 to index
      %extracted = tensor.extract %collapsed_113[%246] : tensor<48xf32>
      linalg.yield %extracted : f32
    } -> tensor<32xf32>
    %expanded_120 = tensor.expand_shape %161 [[0, 1]] output_shape [8, 4] : tensor<32xf32> into tensor<8x4xf32>
    %162 = tensor.empty() : tensor<4xf32>
    %163 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%145 : tensor<4xi64>) outs(%162 : tensor<4xf32>) {
    ^bb0(%in: i64, %out: f32):
      %243 = arith.cmpi slt, %in, %c0_i64 : i64
      %244 = arith.addi %in, %c12_i64 : i64
      %245 = arith.select %243, %244, %in : i64
      %246 = arith.index_cast %245 : i64 to index
      %extracted = tensor.extract %cst_31[%246] : tensor<12xf32>
      linalg.yield %extracted : f32
    } -> tensor<4xf32>
    %164 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%153 : tensor<8xi64>) outs(%152 : tensor<8xi64>) {
    ^bb0(%in: i64, %out: i64):
      %243 = arith.addi %in, %c4_i64 : i64
      linalg.yield %243 : i64
    } -> tensor<8xi64>
    %165 = tensor.empty() : tensor<8xf32>
    %166 = linalg.generic {indexing_maps = [#map8, #map8], iterator_types = ["parallel"]} ins(%164 : tensor<8xi64>) outs(%165 : tensor<8xf32>) {
    ^bb0(%in: i64, %out: f32):
      %243 = arith.cmpi slt, %in, %c0_i64 : i64
      %244 = arith.addi %in, %c12_i64 : i64
      %245 = arith.select %243, %244, %in : i64
      %246 = arith.index_cast %245 : i64 to index
      %extracted = tensor.extract %cst_31[%246] : tensor<12xf32>
      linalg.yield %extracted : f32
    } -> tensor<8xf32>
    %collapsed_121 = tensor.collapse_shape %transposed_111 [[0], [1, 2]] : tensor<3x1x4xf32> into tensor<3x4xf32>
    %transposed_122 = linalg.transpose ins(%expanded_117 : tensor<4x4xf32>) outs(%38 : tensor<4x4xf32>) permutation = [1, 0] 
    %167 = linalg.matmul ins(%collapsed_121, %transposed_122 : tensor<3x4xf32>, tensor<4x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %168 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%167, %163 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %collapsed_123 = tensor.collapse_shape %transposed_112 [[0], [1, 2]] : tensor<3x1x4xf32> into tensor<3x4xf32>
    %transposed_124 = linalg.transpose ins(%expanded_120 : tensor<8x4xf32>) outs(%66 : tensor<4x8xf32>) permutation = [1, 0] 
    %169 = linalg.matmul ins(%collapsed_123, %transposed_124 : tensor<3x4xf32>, tensor<4x8xf32>) outs(%68 : tensor<3x8xf32>) -> tensor<3x8xf32>
    %170 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%169, %166 : tensor<3x8xf32>, tensor<8xf32>) outs(%67 : tensor<3x8xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x8xf32>
    %expanded_125 = tensor.expand_shape %170 [[0, 1], [2, 3, 4]] output_shape [1, 3, 1, 2, 4] : tensor<3x8xf32> into tensor<1x3x1x2x4xf32>
    %171 = tensor.empty() : tensor<2x3x1x1x4xf32>
    %transposed_126 = linalg.transpose ins(%expanded_125 : tensor<1x3x1x2x4xf32>) outs(%171 : tensor<2x3x1x1x4xf32>) permutation = [3, 1, 2, 0, 4] 
    %collapsed_127 = tensor.collapse_shape %transposed_126 [[0], [1], [2, 3], [4]] : tensor<2x3x1x1x4xf32> into tensor<2x3x1x4xf32>
    %extracted_slice_128 = tensor.extract_slice %collapsed_127[0, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<2x3x1x4xf32> to tensor<1x3x1x4xf32>
    %extracted_slice_129 = tensor.extract_slice %collapsed_127[1, 0, 0, 0] [1, 3, 1, 4] [1, 1, 1, 1] : tensor<2x3x1x4xf32> to tensor<1x3x1x4xf32>
    %expanded_130 = tensor.expand_shape %168 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_131 = linalg.transpose ins(%expanded_130 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_132 = tensor.collapse_shape %extracted_slice_128 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_133 = tensor.expand_shape %collapsed_132 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_134 = linalg.transpose ins(%expanded_133 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %collapsed_135 = tensor.collapse_shape %extracted_slice_129 [[0, 1], [2, 3]] : tensor<1x3x1x4xf32> into tensor<3x4xf32>
    %expanded_136 = tensor.expand_shape %collapsed_135 [[0], [1, 2]] output_shape [3, 2, 2] : tensor<3x4xf32> into tensor<3x2x2xf32>
    %transposed_137 = linalg.transpose ins(%expanded_136 : tensor<3x2x2xf32>) outs(%7 : tensor<2x3x2xf32>) permutation = [1, 0, 2] 
    %expanded_138 = tensor.expand_shape %transposed_131 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %expanded_139 = tensor.expand_shape %transposed_134 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %172 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_138 : tensor<1x2x3x2xf32>) outs(%8 : tensor<1x2x3x2xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x3x2xf32>
    %transposed_140 = linalg.transpose ins(%expanded_139 : tensor<1x2x3x2xf32>) outs(%10 : tensor<1x2x2x3xf32>) permutation = [0, 1, 3, 2] 
    %173 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%transposed_140 : tensor<1x2x2x3xf32>) outs(%10 : tensor<1x2x2x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_7 : f64 to f32
      %244 = arith.mulf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x2x2x3xf32>
    %collapsed_141 = tensor.collapse_shape %172 [[0, 1], [2], [3]] : tensor<1x2x3x2xf32> into tensor<2x3x2xf32>
    %collapsed_142 = tensor.collapse_shape %173 [[0, 1], [2], [3]] : tensor<1x2x2x3xf32> into tensor<2x2x3xf32>
    %174 = linalg.batch_matmul ins(%collapsed_141, %collapsed_142 : tensor<2x3x2xf32>, tensor<2x2x3xf32>) outs(%13 : tensor<2x3x3xf32>) -> tensor<2x3x3xf32>
    %expanded_143 = tensor.expand_shape %174 [[0, 1], [2], [3]] output_shape [1, 2, 3, 3] : tensor<2x3x3xf32> into tensor<1x2x3x3xf32>
    %175:2 = linalg.generic {indexing_maps = [#map2, #map3, #map3], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%expanded_143 : tensor<1x2x3x3xf32>) outs(%18, %16 : tensor<1x2x3xf32>, tensor<1x2x3xi64>) {
    ^bb0(%in: f32, %out: f32, %out_158: i64):
      %243 = linalg.index 3 : index
      %244 = arith.index_cast %243 : index to i64
      %245 = arith.maximumf %in, %out : f32
      %246 = arith.cmpf ogt, %in, %out : f32
      %247 = arith.select %246, %244, %out_158 : i64
      linalg.yield %245, %247 : f32, i64
    } -> (tensor<1x2x3xf32>, tensor<1x2x3xi64>)
    %expanded_144 = tensor.expand_shape %175#0 [[0], [1], [2, 3]] output_shape [1, 2, 3, 1] : tensor<1x2x3xf32> into tensor<1x2x3x1xf32>
    %176 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_143, %expanded_144 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %177 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%176 : tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.exp %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %178 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%177 : tensor<1x2x3x3xf32>) outs(%24 : tensor<1x2x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x1xf32>
    %179 = linalg.generic {indexing_maps = [#map2, #map4, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%177, %178 : tensor<1x2x3x3xf32>, tensor<1x2x3x1xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.divf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %180 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%expanded_143 : tensor<1x2x3x3xf32>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: f32, %out: i1):
      %243 = arith.extf %in : f32 to f64
      %244 = arith.cmpf oeq, %243, %cst_6 : f64
      linalg.yield %244 : i1
    } -> tensor<1x2x3x3xi1>
    %181 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%180 : tensor<1x2x3x3xi1>) outs(%27 : tensor<1x2x3x3xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x3xi1>
    %182 = linalg.generic {indexing_maps = [#map2, #map4], iterator_types = ["parallel", "parallel", "parallel", "reduction"]} ins(%181 : tensor<1x2x3x3xi1>) outs(%31 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.ori %in, %out : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %183 = linalg.generic {indexing_maps = [#map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%182 : tensor<1x2x3x1xi1>) outs(%30 : tensor<1x2x3x1xi1>) {
    ^bb0(%in: i1, %out: i1):
      %243 = arith.cmpi eq, %in, %false : i1
      linalg.yield %243 : i1
    } -> tensor<1x2x3x1xi1>
    %184 = linalg.generic {indexing_maps = [#map4, #map2, #map2, #map2], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%183, %cst_44, %179 : tensor<1x2x3x1xi1>, tensor<1x2x3x3xf32>, tensor<1x2x3x3xf32>) outs(%20 : tensor<1x2x3x3xf32>) {
    ^bb0(%in: i1, %in_158: f32, %in_159: f32, %out: f32):
      %243 = arith.select %in, %in_158, %in_159 : f32
      linalg.yield %243 : f32
    } -> tensor<1x2x3x3xf32>
    %collapsed_145 = tensor.collapse_shape %184 [[0, 1], [2], [3]] : tensor<1x2x3x3xf32> into tensor<2x3x3xf32>
    %185 = linalg.batch_matmul ins(%collapsed_145, %transposed_137 : tensor<2x3x3xf32>, tensor<2x3x2xf32>) outs(%35 : tensor<2x3x2xf32>) -> tensor<2x3x2xf32>
    %expanded_146 = tensor.expand_shape %185 [[0, 1], [2], [3]] output_shape [1, 2, 3, 2] : tensor<2x3x2xf32> into tensor<1x2x3x2xf32>
    %transposed_147 = linalg.transpose ins(%expanded_146 : tensor<1x2x3x2xf32>) outs(%37 : tensor<3x1x2x2xf32>) permutation = [2, 0, 1, 3] 
    %collapsed_148 = tensor.collapse_shape %transposed_147 [[0], [1, 2, 3]] : tensor<3x1x2x2xf32> into tensor<3x4xf32>
    %transposed_149 = linalg.transpose ins(%cst_32 : tensor<4x4xf32>) outs(%38 : tensor<4x4xf32>) permutation = [1, 0] 
    %186 = linalg.matmul ins(%collapsed_148, %transposed_149 : tensor<3x4xf32>, tensor<4x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %187 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%186, %cst_33 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %expanded_150 = tensor.expand_shape %187 [[0], [1, 2]] output_shape [3, 1, 4] : tensor<3x4xf32> into tensor<3x1x4xf32>
    %transposed_151 = linalg.transpose ins(%expanded_150 : tensor<3x1x4xf32>) outs(%43 : tensor<1x3x4xf32>) permutation = [1, 0, 2] 
    %188 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%143, %transposed_151 : tensor<1x3x4xf32>, tensor<1x3x4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %189 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%188 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %190 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%189 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %191 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%190 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %192 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%189, %191 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %193 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%192, %192 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %194 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%193 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %195 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%194 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %196 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%195 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %197 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%188 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %198 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%197 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %199 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%196 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %200 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%199 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %201 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%188, %198 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %202 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%201, %200 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %203 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%202, %cst_34 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %204 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%203, %cst_35 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %collapsed_152 = tensor.collapse_shape %204 [[0, 1], [2]] : tensor<1x3x4xf32> into tensor<3x4xf32>
    %transposed_153 = linalg.transpose ins(%cst_36 : tensor<8x4xf32>) outs(%66 : tensor<4x8xf32>) permutation = [1, 0] 
    %205 = linalg.matmul ins(%collapsed_152, %transposed_153 : tensor<3x4xf32>, tensor<4x8xf32>) outs(%68 : tensor<3x8xf32>) -> tensor<3x8xf32>
    %206 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%205, %cst_37 : tensor<3x8xf32>, tensor<8xf32>) outs(%67 : tensor<3x8xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x8xf32>
    %expanded_154 = tensor.expand_shape %206 [[0, 1], [2]] output_shape [1, 3, 8] : tensor<3x8xf32> into tensor<1x3x8xf32>
    %207 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_154 : tensor<1x3x8xf32>) outs(%71 : tensor<1x3x8xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_10 : f32
      %244 = math.erf %243 : f32
      %245 = arith.addf %244, %cst_3 : f32
      %246 = arith.mulf %245, %cst_4 : f32
      %247 = arith.mulf %in, %246 : f32
      linalg.yield %247 : f32
    } -> tensor<1x3x8xf32>
    %collapsed_155 = tensor.collapse_shape %207 [[0, 1], [2]] : tensor<1x3x8xf32> into tensor<3x8xf32>
    %transposed_156 = linalg.transpose ins(%cst_38 : tensor<4x8xf32>) outs(%73 : tensor<8x4xf32>) permutation = [1, 0] 
    %208 = linalg.matmul ins(%collapsed_155, %transposed_156 : tensor<3x8xf32>, tensor<8x4xf32>) outs(%40 : tensor<3x4xf32>) -> tensor<3x4xf32>
    %209 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%208, %cst_39 : tensor<3x4xf32>, tensor<4xf32>) outs(%39 : tensor<3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<3x4xf32>
    %expanded_157 = tensor.expand_shape %209 [[0, 1], [2]] output_shape [1, 3, 4] : tensor<3x4xf32> into tensor<1x3x4xf32>
    %210 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%204, %expanded_157 : tensor<1x3x4xf32>, tensor<1x3x4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %211 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%210 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %212 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%211 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %213 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%212 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %214 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%211, %213 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %215 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%214, %214 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %216 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%215 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %217 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%216 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %218 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%217 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %219 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%210 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %220 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%219 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %221 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%218 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %222 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%221 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %223 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%210, %220 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %224 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%223, %222 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %225 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%224, %cst_40 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %226 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%225, %cst_41 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %227 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%226 : tensor<1x3x4xf32>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f32, %out: f64):
      %243 = arith.extf %in : f32 to f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %228 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%227 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %229 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%228 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %230 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%227, %229 : tensor<1x3x4xf64>, tensor<1x3x1xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.subf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %231 = linalg.generic {indexing_maps = [#map5, #map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%230, %230 : tensor<1x3x4xf64>, tensor<1x3x4xf64>) outs(%45 : tensor<1x3x4xf64>) {
    ^bb0(%in: f64, %in_158: f64, %out: f64):
      %243 = arith.mulf %in, %in_158 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x4xf64>
    %232 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%231 : tensor<1x3x4xf64>) outs(%48 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.addf %in, %out : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %233 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%232 : tensor<1x3x1xf64>) outs(%47 : tensor<1x3x1xf64>) {
    ^bb0(%in: f64, %out: f64):
      %243 = arith.divf %in, %cst_8 : f64
      linalg.yield %243 : f64
    } -> tensor<1x3x1xf64>
    %234 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%233 : tensor<1x3x1xf64>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f64, %out: f32):
      %243 = arith.truncf %in : f64 to f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %235 = linalg.generic {indexing_maps = [#map5, #map6], iterator_types = ["parallel", "parallel", "reduction"]} ins(%226 : tensor<1x3x4xf32>) outs(%57 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.addf %in, %out : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %236 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%235 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.divf %in, %cst_9 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %237 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%234 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = arith.truncf %cst_5 : f64 to f32
      %244 = arith.addf %in, %243 : f32
      linalg.yield %244 : f32
    } -> tensor<1x3x1xf32>
    %238 = linalg.generic {indexing_maps = [#map5, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%237 : tensor<1x3x1xf32>) outs(%55 : tensor<1x3x1xf32>) {
    ^bb0(%in: f32, %out: f32):
      %243 = math.rsqrt %in : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x1xf32>
    %239 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%226, %236 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.subf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %240 = linalg.generic {indexing_maps = [#map5, #map6, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%239, %238 : tensor<1x3x4xf32>, tensor<1x3x1xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %241 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%240, %cst_42 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.mulf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    %242 = linalg.generic {indexing_maps = [#map5, #map7, #map5], iterator_types = ["parallel", "parallel", "parallel"]} ins(%241, %cst_43 : tensor<1x3x4xf32>, tensor<4xf32>) outs(%43 : tensor<1x3x4xf32>) {
    ^bb0(%in: f32, %in_158: f32, %out: f32):
      %243 = arith.addf %in, %in_158 : f32
      linalg.yield %243 : f32
    } -> tensor<1x3x4xf32>
    return %242 : tensor<1x3x4xf32>
  }
}

{-#
  dialect_resources: {
    builtin: {
      torch_tensor_12_4_torch.float32: "0x040000000AD7A33C0AD7233D8FC2753D0AD7A33DCDCCCC3D8FC2F53D295C0F3E0AD7233EEC51383ECDCC4C3EAE47613E8FC2753EB81E853E295C8F3E9A99993E0AD7A33E7B14AE3EEC51B83E5C8FC23ECDCCCC3E3D0AD73EAE47E13E1F85EB3E8FC2F53E0000003FB81E053F713D0A3F295C0F3FE17A143F9A99193F52B81E3F0AD7233FC3F5283F7B142E3F3333333FEC51383FA4703D3F5C8F423F14AE473FCDCC4C3F85EB513F3D0A573FF6285C3FAE47613F6666663F1F856B3FD7A3703F8FC2753F",
      torch_tensor_12_torch.float32: "0x04000000C337223CC337A23CA553F33CC337223DB4C54A3DA553733DCBF08D3DC337A23DBC7EB63DB4C5CA3DAC0CDF3DA553F33D",
      torch_tensor_4_4_torch.float32: "0x04000000D9899D3CD9891D3DC54E6C3DD9899D3D4FECC43DC54EEC3D9ED8093ED9891D3E143B313E4FEC443E8A9D583EC54E6C3E0000803E9ED8893E3BB1933ED9899D3E",
      torch_tensor_4_torch.float32: "0x0400000066111F3C66119F3C199AEE3C66111F3D",
      torch_tensor_4_torch.float32_1: "0x0400000026B4173C26B4973C398EE33C26B4173D",
      torch_tensor_4_torch.float32_2: "0x04000000DA4F163CDA4F963CC877E13CDA4F163D",
      torch_tensor_8_4_torch.float32: "0x0400000026B4973C26B4173D398E633D26B4973D2FA1BD3D398EE33DA1BD043E26B4173EABAA2A3E2FA13D3EB497503E398E633EBE84763EA1BD843EE4388E3E26B4973E682FA13EABAAAA3EED25B43E2FA1BD3E721CC73EB497D03EF712DA3E398EE33E7B09ED3EBE84F63E0000003FA1BD043F427B093FE4380E3F85F6123F26B4173F",
      torch_tensor_8_torch.float32: "0x04000000C1091C3CC1099C3CA10EEA3CC1091C3D310C433DA10E6A3D8988883DC1099C3D",
      torch_tensor_4_8_torch.float32: "0x040000002549923C2549123DB76D5B3D2549923D6EDBB63DB76DDB3D0000003E2549123E4992243E6EDB363E9224493EB76D5B3EDBB66D3E0000803E9224893E2549923EB76D9B3E4992A43EDBB6AD3E6EDBB63E0000C03E9224C93E2549D23EB76DDB3E4992E43EDBB6ED3E6EDBF63E0000003F4992043F9224093FDBB60D3F2549123F",
      torch_tensor_4_torch.float32_3: "0x040000001A1F193C1A1F993CA7AEE53C1A1F193D",
      torch_tensor_4_torch.float32_4: "0x0400000009F2143C09F2943C0E6BDF3C09F2143D",
      torch_tensor_4_torch.float32_5: "0x04000000869A133C869A933CC967DD3C869A133D",
      torch_tensor_4_torch.float32_6: "0x040000002549123C2549923CB76DDB3C2549123D",
      torch_tensor_4_torch.float32_7: "0x04000000BCFD103CBCFD903C9A7CD93CBCFD103D",
      torch_tensor_12_4_torch.float32_1: "0x040000000000803C0000003D0000403D0000803D0000A03D0000C03D0000E03D0000003E0000103E0000203E0000303E0000403E0000503E0000603E0000703E0000803E0000883E0000903E0000983E0000A03E0000A83E0000B03E0000B83E0000C03E0000C83E0000D03E0000D83E0000E03E0000E83E0000F03E0000F83E0000003F0000043F0000083F00000C3F0000103F0000143F0000183F00001C3F0000203F0000243F0000283F00002C3F0000303F0000343F0000383F00003C3F0000403F",
      torch_tensor_12_torch.float32_1: "0x0400000035780E3C35788E3C50B4D53C35780E3D4316323D50B4553D5D52793D35788E3D3C47A03D4316B23D49E5C33D50B4D53D",
      torch_tensor_4_4_torch.float32_1: "0x04000000103E783C103EF83C8C2E3A3D103E783DCA269B3D8C2EBA3D4E36D93D103EF83DE9A20B3ECA261B3EABAA2A3E8C2E3A3E6DB2493E4E36593E2FBA683E103E783E",
      torch_tensor_4_torch.float32_8: "0x04000000C1080C3CC1088C3C210DD23CC1080C3D",
      torch_tensor_4_torch.float32_9: "0x040000002108023C2108823C310CC33C2108023D",
      torch_tensor_4_torch.float32_10: "0x040000000402013C0402813C0683C13C0402013D",
      torch_tensor_12_4_torch.float32_2: "0x04000000F1F0703CF1F0F03CB5B4343DF1F0703D9796963DB5B4B43DD3D2D23DF1F0F03D8887073E9796163EA6A5253EB5B4343EC4C3433ED3D2523EE2E1613EF1F0703E0000803E8887873E0F0F8F3E9796963E1E1E9E3EA6A5A53E2D2DAD3EB5B4B43E3C3CBC3EC4C3C33E4B4BCB3ED3D2D23E5A5ADA3EE2E1E13E6969E93EF1F0F03E7878F83E0000003FC4C3033F8887073F4B4B0B3F0F0F0F3FD3D2123F9796163F5A5A1A3F1E1E1E3FE2E1213FA6A5253F6969293F2D2D2D3FF1F0303FB5B4343F",
      torch_tensor_12_torch.float32_2: "0x0400000041AE093C41AE893C6185CE3C41AE093DD1192C3D61854E3DF1F0703D41AE893D09E49A3DD119AC3D994FBD3D6185CE3D",
      torch_tensor_4_4_torch.float32_2: "0x04000000A10E6A3CA10EEA3CF98A2F3DA10E6A3D2549923DF98AAF3DCDCCCC3DA10EEA3D3BA8033E2549123E0FEA203EF98A2F3EE32B3E3ECDCC4C3EB76D5B3EA10E6A3E",
      torch_tensor_4_torch.float32_11: "0x04000000AB67073CAB67873C811BCB3CAB67073D",
      torch_tensor_4_torch.float32_12: "0x040000000000003C0000803C0000C03C0000003D",
      torch_tensor_4_torch.float32_13: "0x04000000F803FE3BF8037E3CFA82BE3CF803FE3C",
      torch_tensor_8_4_torch.float32_1: "0x04000000398E633C398EE33CABAA2A3D398E633DE4388E3DABAAAA3D721CC73D398EE33D0000003EE4380E3EC7711C3EABAA2A3E8EE3383E721C473E5555553E398E633E1CC7713E0000803E721C873EE4388E3E5555953EC7719C3E398EA33EABAAAA3E1CC7B13E8EE3B83E0000C03E721CC73EE438CE3E5555D53EC771DC3E398EE33E",
      torch_tensor_8_torch.float32_1: "0x040000000834053C0834853C0CCEC73C0834053D0A81263D0CCE473D0F1B693D0834853D",
      torch_tensor_4_8_torch.float32_1: "0x04000000C9675D3CC967DD3CD60D263DC9675D3DDD608A3DD60DA63DD0BAC13DC967DD3DC214F93DDD600A3E5A37183ED60D263E53E4333ED0BA413E4C914F3EC9675D3E453E6B3EC214793E9F75833EDD608A3E1C4C913E5A37983E98229F3ED60DA63E15F9AC3E53E4B33E91CFBA3ED0BAC13E0EA6C83E4C91CF3E8A7CD63EC967DD3E",
      torch_tensor_4_torch.float32_14: "0x040000006F12033C6F12833CA69BC43C6F12033D",
      torch_tensor_4_torch.float32_15: "0x04000000C10FFC3BC10F7C3CD10BBD3CC10FFC3C",
      torch_tensor_4_torch.float32_16: "0x040000002D23FA3B2D237A3C629ABB3C2D23FA3C",
      torch_tensor_4_torch.float32_17: "0x04000000103EF83B103E783C8C2EBA3C103EF83C",
      torch_tensor_4_torch.float32_18: "0x040000003E60F63B3E60763C2EC8B83C3E60F63C"
    }
  }
#-}

