site_name: sculptor-mlir
site_description: Documentation for the sculptor-mlir compiler.
repo_url: https://github.com/PlatinumCD/sculptor-mlir
repo_name: PlatinumCD/sculptor-mlir

docs_dir: pages
site_dir: ../site

exclude_docs: |
  *.log

theme:
  name: terminal

extra_css:
  - css/site.css

extra_javascript:
  - js/open-github-link.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      guess_lang: false
      noclasses: true
      pygments_style: friendly
      use_pygments: true
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Design: design.md
  - Walkthrough: walkthrough.md
  - Placement: placement.md
  - GitHub: https://github.com/PlatinumCD/sculptor-mlir
